runtime: php72
env: standard
instance_class: F1
service: default

handlers:
  - url: /stylesheets/(.*)
    static_files: stylesheets/\1
    require_matching_file: false
    upload: stylesheets/.*
  - url: /(.+\.(gif|png|jpg|svg|css|csv|js|txt|pdf|json|bin))$
    static_files: \1
    require_matching_file: false
    upload: .+\.(gif|png|jpg|svg|css|csv|py|js|txt|pdf|json|bin)$
  - url: .*
    script: auto
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
network: {}
env_variables:
  GOOGLE_STORAGE_BUCKET: neurodatalab.appspot.com
